"use client";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { BookOpen, Braces, Check, ChevronRight, Clipboard, Database, FileCode2, FileText, LocateFixed, Search, Sparkles, Trash2, UploadCloud, X } from "lucide-react";
import { AnchoredMarkdown } from "@/components/anchor/AnchoredMarkdown";
import { EmptyState } from "@/components/common/EmptyState";
import { api, type Citation, type DocumentDetail, type DocumentItem, type SearchHit } from "@/lib/api";

const modes = [{ id: "keyword", label: "关键词" }, { id: "semantic", label: "语义" }, { id: "hybrid", label: "混合" }];
const icons = { paper: FileText, note: BookOpen, code: FileCode2, other: Database };

export default function KnowledgePage() {
  const [documents, setDocuments] = useState<DocumentItem[]>([]); const [loading, setLoading] = useState(true);
  const [error, setError] = useState(""); const [query, setQuery] = useState(""); const [mode, setMode] = useState("hybrid");
  const [type, setType] = useState(""); const [year, setYear] = useState(""); const [hits, setHits] = useState<SearchHit[]>([]);
  const [searching, setSearching] = useState(false); const [uploading, setUploading] = useState<string[]>([]); const [dragging, setDragging] = useState(false);
  const [preview, setPreview] = useState<DocumentDetail | null>(null); const [answer, setAnswer] = useState(""); const [citations, setCitations] = useState<Citation[]>([]);
  const [focusedHit, setFocusedHit] = useState<SearchHit | null>(null); const [copied, setCopied] = useState(false);
  const fileRef = useRef<HTMLInputElement>(null);

  const load = useCallback(async () => { try { setLoading(true); setError(""); setDocuments(await api.documents()); } catch (e) { setError((e as Error).message); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => {
    const documentId = new URLSearchParams(window.location.search).get("document");
    if (documentId) api.document(documentId).then(setPreview).catch((reason) => setError(reason instanceof Error ? reason.message : "文档加载失败"));
  }, []);
  const visible = useMemo(() => documents.filter((doc) => !type || doc.type === type), [documents, type]);

  async function upload(files: FileList | File[]) {
    const list = Array.from(files); if (!list.length) return; setUploading(list.map((file) => file.name)); setError("");
    try { for (const file of list) await api.upload(file); await load(); } catch (e) { setError((e as Error).message); } finally { setUploading([]); setDragging(false); }
  }
  async function search() {
    if (!query.trim()) return; setSearching(true); setError(""); setAnswer("");
    try { const filters: Record<string, unknown> = {}; if (type) filters.type = type; if (year) filters.year_gte = Number(year); setHits((await api.search(query, mode, filters)).hits); }
    catch (e) { setError((e as Error).message); } finally { setSearching(false); }
  }
  async function ask() {
    if (!query.trim()) return; setSearching(true); setError("");
    try { const response = await api.qa(query); setAnswer(response.answer); setCitations(response.citations); }
    catch (e) { setError((e as Error).message); } finally { setSearching(false); }
  }
  async function openDocument(id: string, hit: SearchHit | null = null) { try { setFocusedHit(hit); setPreview(await api.document(id)); } catch (e) { setError((e as Error).message); } }
  async function copyHash() { if (!preview) return; await navigator.clipboard.writeText(preview.storage_hash); setCopied(true); window.setTimeout(() => setCopied(false), 1800); }
  async function remove(id: string) { if (!confirm("删除该文档及全部切块？")) return; try { await api.deleteDocument(id); await load(); setPreview(null); } catch (e) { setError((e as Error).message); } }
  function anchorClick(anchor: string) { const citation = citations.find((item) => item.anchor.toLowerCase() === anchor.toLowerCase()); if (citation) void openDocument(citation.document_id); }

  return <div className="mx-auto max-w-[1280px] p-4 md:p-6">
    <div className="mb-6 flex items-end justify-between gap-4"><div><div className="label">资料与数据</div><h1 className="mt-1 text-2xl font-semibold tracking-tight">知识库</h1><p className="mt-1 text-sm text-slate-500">把论文、数据和笔记放在一起检索，回答可回到原文。</p></div><button onClick={() => fileRef.current?.click()} className="btn-primary shrink-0"><UploadCloud size={16}/>上传文件</button><input ref={fileRef} className="hidden" type="file" multiple accept=".pdf,.csv,.xlsx,.py,.ipynb,.md,.txt" onChange={(e) => e.target.files && void upload(e.target.files)}/></div>
    <section className="card p-4">
      <div className="flex flex-col gap-3 lg:flex-row"><div className="flex min-h-11 flex-1 items-center gap-3 rounded-xl border bg-white px-4 dark:border-slate-700 dark:bg-slate-950"><Search size={18} className="text-slate-400"/><input value={query} onChange={(e) => setQuery(e.target.value)} onKeyDown={(e) => e.key === "Enter" && void search()} className="min-w-0 flex-1 bg-transparent outline-none" placeholder="检索观点、方法、数据或结论…"/>{searching && <span className="h-2 w-2 animate-pulse rounded-full bg-amber-500"/>}</div><div className="flex rounded-lg bg-slate-100 p-1 dark:bg-slate-800">{modes.map((item) => <button key={item.id} onClick={() => setMode(item.id)} className={`rounded-md px-3 py-2 text-xs font-medium transition ${mode === item.id ? "bg-white text-brand shadow-sm dark:bg-slate-700" : "text-slate-500"}`}>{item.label}</button>)}</div><button onClick={() => void search()} disabled={searching || !query.trim()} className="btn-primary">检索</button><button onClick={() => void ask()} disabled={searching || !query.trim()} className="btn-secondary"><Sparkles size={15}/>问答</button></div>
      <div className="mt-3 flex flex-wrap items-center gap-2 border-t pt-3"><span className="text-xs text-slate-400">筛选</span><select value={type} onChange={(e) => setType(e.target.value)} className="input h-8 text-xs"><option value="">全部类型</option><option value="paper">论文</option><option value="note">笔记</option><option value="code">代码</option><option value="other">数据集/其它</option></select><input value={year} onChange={(e) => setYear(e.target.value)} className="input h-8 w-28 text-xs" inputMode="numeric" placeholder="年份 ≥"/><span className="ml-auto text-xs text-slate-400">{documents.length} 个文件</span></div>
    </section>
    {error && <div role="alert" className="mt-4 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700"><strong>操作失败：</strong>{error} <button onClick={() => setError("")} className="ml-2 underline">关闭</button></div>}
    {answer && <section className="card mt-4 border-blue-200 p-5"><div className="mb-3 flex items-center gap-2 text-xs font-semibold uppercase tracking-wide text-brand"><Sparkles size={14}/>基于知识库的回答</div><AnchoredMarkdown text={answer} onAnchor={anchorClick}/><div className="mt-4 flex flex-wrap gap-2">{citations.map((item) => <button onClick={() => void openDocument(item.document_id)} key={item.chunk_id} className="rounded-lg border px-2 py-1 font-mono text-xs text-slate-500 hover:border-brand hover:text-brand">{item.anchor} · 查看来源文档</button>)}</div></section>}
    {hits.length > 0 && <section className="mt-5"><div className="mb-3 flex items-center justify-between"><h2 className="font-semibold">检索结果</h2><span className="text-xs text-slate-400">按融合/重排分数排序</span></div><div className="space-y-2">{hits.map((hit, index) => <article key={hit.chunk_id} className="card group p-4"><div className="flex gap-3"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-md bg-blue-50 text-xs font-semibold text-brand">{index + 1}</span><div className="min-w-0 flex-1"><div className="mb-2 flex items-center gap-2 text-xs text-slate-400"><span>{hit.section || "未命名章节"}</span><span>·</span><span>位置 {hit.position ?? "—"}</span><span className="ml-auto font-mono">{hit.score.toFixed(4)}</span></div><p className="line-clamp-3 leading-6 text-slate-700 dark:text-slate-200">{hit.content}</p><button onClick={() => void openDocument(hit.document_id, hit)} className="mt-3 inline-flex items-center gap-1 text-xs font-medium text-brand"><LocateFixed size={13}/>查看命中片段</button></div></div></article>)}</div></section>}
    <section className="mt-6"><div className="mb-3 flex items-center justify-between"><h2 className="font-semibold">全部文件</h2><span className="text-xs text-slate-400">拖入下方区域即可入库</span></div><div onDragEnter={(e) => { e.preventDefault(); setDragging(true); }} onDragOver={(e) => e.preventDefault()} onDragLeave={(e) => { if (e.currentTarget === e.target) setDragging(false); }} onDrop={(e) => { e.preventDefault(); void upload(e.dataTransfer.files); }} className={`min-h-60 rounded-xl border-2 border-dashed p-3 transition ${dragging ? "border-brand bg-blue-50/70 dark:bg-blue-950/20" : "border-slate-200 dark:border-slate-700"}`}>
      {uploading.length > 0 && <div className="mb-3 flex items-center gap-3 rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800"><UploadCloud className="animate-bounce" size={17}/><span>正在解析与向量化：{uploading.join("、")}</span></div>}
      {loading ? <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{Array.from({ length: 6 }).map((_, i) => <div key={i} className="h-36 animate-pulse rounded-xl bg-slate-100 dark:bg-slate-800"/>)}</div> : visible.length === 0 ? <EmptyState title="从第一份资料开始" description="上传论文用于检索和引用，上传 CSV 或 XLSX 后即可在分析页直接使用。" action={<button onClick={() => fileRef.current?.click()} className="btn-primary"><UploadCloud size={15}/>选择文件</button>}/> : <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{visible.map((doc) => { const Icon = icons[doc.type]; return <button key={doc.id} onClick={() => void openDocument(doc.id)} className="card group p-4 text-left transition hover:-translate-y-0.5 hover:border-blue-200"><div className="flex items-start gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-lg bg-slate-100 text-slate-600 group-hover:bg-blue-50 group-hover:text-brand dark:bg-slate-800"><Icon size={19}/></span><div className="min-w-0 flex-1"><div className="truncate font-medium">{doc.title || doc.filename}</div><div className="mt-1 truncate text-xs text-slate-400">{doc.filename}</div></div><ChevronRight size={15} className="text-slate-300"/></div><div className="mt-5 flex items-center gap-2"><span className="rounded-md bg-slate-100 px-2 py-1 text-[11px] text-slate-500 dark:bg-slate-800">{doc.type}</span>{doc.year && <span className="text-xs text-slate-400">{doc.year}</span>}<span className="ml-auto font-mono text-[10px] text-slate-300">{doc.id.slice(0, 8)}</span></div></button>; })}</div>}
    </div></section>
    {preview && <div className="fixed inset-0 z-50 bg-slate-950/25" onMouseDown={() => { setPreview(null); setFocusedHit(null); }}><aside className="absolute bottom-0 right-0 top-0 w-full max-w-lg overflow-y-auto border-l bg-white p-6 shadow-2xl dark:border-slate-800 dark:bg-slate-950" onMouseDown={(e) => e.stopPropagation()}><div className="flex items-start gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-blue-50 text-brand"><Braces size={20}/></span><div className="min-w-0 flex-1"><h2 className="truncate text-lg font-semibold">{preview.title || preview.filename}</h2><p className="mt-1 text-xs text-slate-400">{preview.filename}</p></div><button onClick={() => { setPreview(null); setFocusedHit(null); }} className="btn-secondary h-8 w-8 px-0" aria-label="关闭"><X size={15}/></button></div>{focusedHit && <section className="mt-6 rounded-xl border border-blue-200 bg-blue-50 p-4 dark:border-blue-900 dark:bg-blue-950/30"><div className="flex items-center gap-2 text-xs font-semibold text-brand"><LocateFixed size={14}/>检索命中片段</div><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-slate-700 dark:text-slate-200">{focusedHit.content}</p><div className="mt-3 text-xs text-slate-500">{focusedHit.section || "未命名章节"} · 位置 {focusedHit.position ?? "—"}</div></section>}<dl className="mt-6 grid grid-cols-2 gap-4 text-sm"><div><dt className="label">类型</dt><dd className="mt-1">{preview.type}</dd></div><div><dt className="label">年份</dt><dd className="mt-1">{preview.year ?? "—"}</dd></div><div className="col-span-2"><dt className="label">SHA-256 内容指纹</dt><dd className="mt-1 break-all font-mono text-xs text-slate-500">{preview.storage_hash}</dd></div><div><dt className="label">文本切块</dt><dd className="mt-1">{preview.chunks_count}</dd></div><div><dt className="label">DOI</dt><dd className="mt-1 truncate">{preview.doi ?? "—"}</dd></div></dl>{preview.schema_json && <div className="mt-6"><div className="flex items-center justify-between"><h3 className="font-semibold">数据结构</h3><span className="text-xs text-slate-400">{preview.schema_json.row_count} 行</span></div><div className="mt-2 overflow-hidden rounded-lg border"><table className="w-full text-left text-xs"><thead className="bg-slate-50 text-slate-500 dark:bg-slate-900"><tr><th className="px-3 py-2">字段</th><th className="px-3 py-2">类型</th></tr></thead><tbody>{preview.schema_json.columns?.map((column) => <tr key={column.name} className="border-t"><td className="px-3 py-2 font-mono">{column.name}</td><td className="px-3 py-2 text-slate-500">{column.dtype}</td></tr>)}</tbody></table></div></div>}<div className="mt-8 flex gap-2"><button onClick={() => void remove(preview.id)} className="btn-secondary text-red-600"><Trash2 size={15}/>删除</button><button onClick={() => void copyHash()} className="btn-secondary ml-auto">{copied ? <Check size={15}/> : <Clipboard size={15}/>} {copied ? "已复制" : "复制内容指纹"}</button></div></aside></div>}
  </div>;
}
