import { ArrowRight, BookOpen, Brain, Database, FileCheck2, FlaskConical, HelpCircle, Lightbulb, Network, PlayCircle, ShieldCheck } from "lucide-react";
import Link from "next/link";

const workflow = [
  { number: "01", title: "资料入库", text: "上传数据、论文、笔记或代码，建立内容指纹和检索切块。", href: "/knowledge", icon: Database },
  { number: "02", title: "提出分析问题", text: "选择数据，用自己的话描述要比较、检验或解释什么。", href: "/analysis", icon: FlaskConical },
  { number: "03", title: "查看溯源", text: "从产物锚点进入血缘图，查看原始数据、代码、环境和输出。", href: "/analysis", icon: Network },
  { number: "04", title: "校验写作", text: "检查数字、引用与图表，修复问题，通过后回写可信结论。", href: "/writing", icon: FileCheck2 },
];

const capabilities = [
  { title: "知识库", text: "文件入库、混合检索、文献问答与原文定位。", href: "/knowledge", icon: BookOpen },
  { title: "数据分析", text: "根据问题生成并运行代码，失败时尝试修正，并登记每项结果。", href: "/analysis", icon: FlaskConical },
  { title: "复现与漂移", text: "固定随机种子重跑；数值按容差、文件按内容哈希比较。", href: "/lineage", icon: Network },
  { title: "结论检查", text: "检查无来源数字、错误引用和无法复现的图表。", href: "/writing", icon: ShieldCheck },
  { title: "科研记忆", text: "记住研究偏好与方法，并按语义相关性和时效召回。", href: "/memory", icon: Brain },
  { title: "主动建议与技能", text: "建议必须绑定真实证据；技能包只作为可选加速模板。", href: "/analysis", icon: Lightbulb },
];

export default function GuidePage() {
  return <div className="mx-auto max-w-6xl space-y-9 p-5 lg:p-8">
    <section className="aurora-hero p-7 lg:p-10"><span className="aurora-orb -left-16 bottom-0 h-52 w-52 bg-indigo-300/30"/><span className="aurora-orb -right-10 top-0 h-56 w-56 bg-blue-200/25"/><div className="relative grid gap-8 lg:grid-cols-[1fr_320px]"><div><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[.12em] text-indigo-100"><HelpCircle size={15}/>First research journey</div><h1 className="mt-4 text-4xl font-semibold tracking-[-.05em] sm:text-5xl">第一次使用，<br/>从一条研究链开始。</h1><p className="mt-4 max-w-2xl text-[17px] leading-7 text-indigo-100">上传资料、提出问题、整理结果。其余机制会在需要时自动参与，不需要先理解所有概念。</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/knowledge" className="btn-primary">上传第一份资料<ArrowRight size={15}/></Link><Link href="/demo" className="btn-secondary border-white/[.28] bg-white/10 text-white hover:bg-white/20"><PlayCircle size={15}/>先用示例体验</Link></div><div className="mt-6 flex flex-wrap gap-2 text-xs text-indigo-50"><span className="rounded-full border border-white/[.18] bg-white/[.08] px-3 py-1.5 backdrop-blur">从资料或数据开始</span><span className="rounded-full border border-white/[.18] bg-white/[.08] px-3 py-1.5 backdrop-blur">每步都有明确下一步</span></div></div><div className="rounded-[20px] border border-white/[.18] bg-slate-950/20 p-5 backdrop-blur"><div className="text-xs font-semibold uppercase tracking-[.12em] text-indigo-100">你会得到</div><div className="mt-5 space-y-3"><div className="rounded-xl border border-white/[.10] bg-white/[.08] p-3 transition hover:bg-white/[.14]"><div className="text-xs text-indigo-100">资料</div><div className="mt-1 text-sm font-medium">统一管理与快速检索</div></div><div className="rounded-xl border border-white/[.10] bg-white/[.08] p-3 transition hover:bg-white/[.14]"><div className="text-xs text-indigo-100">分析</div><div className="mt-1 text-sm font-medium">把问题变成可用结果</div></div><div className="rounded-xl border border-white/[.10] bg-white/[.08] p-3 transition hover:bg-white/[.14]"><div className="text-xs text-indigo-100">写作</div><div className="mt-1 text-sm font-medium">把结果整理成报告</div></div></div></div></div></section>

    <section><div className="eyebrow text-brand">3 分钟上手</div><div className="mt-1 flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="section-title">按这四步完成第一次研究闭环</h2><p className="mt-1 text-[17px] text-slate-500">每张卡片都能直接带你去完成对应操作。</p></div><Link href="/knowledge" className="text-[17px] text-brand">从第 1 步开始<ArrowRight className="ml-1 inline" size={14}/></Link></div><div className="mt-5 grid gap-4 md:grid-cols-2">{workflow.map(({ number, title, text, href, icon: Icon }, index) => <Link key={number} href={href} className="interactive-card group flex gap-4"><span className="text-3xl font-semibold text-slate-200 group-hover:text-brand">{number}</span><span className={`grid h-10 w-10 shrink-0 place-items-center rounded-2xl text-white shadow-lg ${index % 2 ? "bg-gradient-to-br from-violet-400 to-fuchsia-600" : "bg-gradient-to-br from-sky-400 to-indigo-600"}`}><Icon size={18}/></span><span><strong className="block">{title}</strong><span className="mt-1 block text-sm leading-6 text-slate-500">{text}</span><span className="mt-3 inline-flex items-center gap-1 text-xs font-medium text-brand">前往此步骤<ArrowRight size={13}/></span></span></Link>)}</div></section>

    <section><div className="label">功能地图</div><h2 className="section-title mt-1">每个能力，都能直接开始。</h2><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{capabilities.map(({ title, text, href, icon: Icon }, index) => <Link key={title} href={href} className="interactive-card group"><span className={`grid h-10 w-10 place-items-center rounded-2xl text-white ${index % 3 === 0 ? "bg-gradient-to-br from-sky-400 to-blue-600" : index % 3 === 1 ? "bg-gradient-to-br from-violet-400 to-indigo-600" : "bg-gradient-to-br from-fuchsia-400 to-violet-600"}`}><Icon size={18}/></span><h3 className="mt-4 font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p><span className="mt-4 inline-flex items-center gap-1 text-sm font-medium text-brand">打开功能<ArrowRight size={14}/></span></Link>)}</div></section>

    <section className="grid gap-4 lg:grid-cols-2"><article className="rounded-xl border border-amber-200 bg-amber-50 p-5 text-amber-950"><h3 className="font-semibold">使用前请确认</h3><ul className="mt-3 space-y-2 text-sm leading-6"><li>• 后端与 PostgreSQL 需要正常运行，动态数据才会显示。</li><li>• 分析、问答与 NLI 需要可用的模型 API Key。</li><li>• Docker 沙箱未启动时，可使用 host 模式开发，但最终复现验收应使用 Docker。</li></ul></article><article className="rounded-xl border border-blue-200 bg-blue-50 p-5 text-blue-950"><h3 className="font-semibold">记住这条原则</h3><p className="mt-3 text-sm leading-6">没有 ⟦art_xxxx⟧ 的数字和没有 ⟦src_xxxx⟧ 的引用，不应直接进入可信结论。先校验，再回写。</p><Link href="/writing" className="mt-4 inline-flex items-center gap-1 text-sm font-medium text-brand">进入写作面板<ArrowRight size={14}/></Link></article></section>
  </div>;
}
