"use client";

import { Check, SearchCode, X, XCircle } from "lucide-react";
import { motion, useReducedMotion } from "framer-motion";
import type { AttributionResult, ReproduceResult } from "@/lib/api";
import { agentSpring } from "@/lib/motion";

export function DiffPanel({ result, attribution, attributing, onAttribute, onClose }: { result: ReproduceResult; attribution?: AttributionResult; attributing: boolean; onAttribute: () => void; onClose: () => void }) {
  const reduceMotion = useReducedMotion();
  return <motion.aside initial={reduceMotion ? false : { x: 420 }} animate={{ x: 0 }} exit={reduceMotion ? undefined : { x: 420 }} transition={reduceMotion ? { duration: 0 } : agentSpring} className="material absolute bottom-0 right-0 top-0 z-30 w-[430px] max-w-full overflow-y-auto border-l p-5"><div className="flex items-start"><div><div className="label">复现结果对比</div><h2 className="mt-1 text-lg font-semibold text-status-err">检测到结果漂移</h2><p className="mt-1 text-xs leading-5 text-muted">同一分析在更新后的输入上得到不同结果，可继续定位最可能的变化来源。</p></div><button onClick={onClose} className="btn-secondary ml-auto h-8 w-8 px-0" aria-label="关闭差异面板"><X size={15}/></button></div><button onClick={onAttribute} disabled={attributing} className="btn-primary mt-4 w-full"><SearchCode size={15}/>{attributing ? "正在逐项定位原因…" : "定位变化原因"}</button><div className="mt-5 space-y-3">{result.comparisons.map((item) => <div key={item.artifact_id} className={`rounded-apple border p-4 ${item.within_tol ? "bg-status-ok/[.06]" : "bg-status-err/[.06]"}`}><div className="flex items-center gap-2"><span className={`grid h-6 w-6 place-items-center rounded-full text-white ${item.within_tol ? "bg-status-ok" : "bg-status-err"}`}>{item.within_tol ? <Check size={13}/> : <XCircle size={13}/>}</span><span className="font-semibold">{item.kind}</span><span className="ml-auto font-mono text-[10px] text-subtle">{item.artifact_id.slice(0, 8)}</span></div><div className="mt-3 grid grid-cols-2 gap-2 text-xs"><Value label="原值" value={item.old}/><Value label="新值" value={item.new}/></div>{!item.within_tol && <div className="mt-2 rounded-appleSm bg-status-err/10 p-2 text-xs text-status-err">差异：{JSON.stringify(item.diff)}</div>}</div>)}</div>{attribution && <section className="mt-5 border-t pt-4"><div className="label">根因定位</div><h3 className="mt-1 font-semibold">最可能造成漂移的因素</h3><p className="mt-1 text-xs leading-5 text-muted">系统逐项回放字段或分组，估算它们对结果变化的贡献。</p>{attribution.attributions.length ? <div className="mt-3 space-y-4">{attribution.attributions.map((item) => <details key={item.dimension} className="group"><summary className="cursor-pointer list-none"><div className="mb-1 flex items-center justify-between gap-3 text-xs"><span className="truncate font-semibold">{item.dimension}</span><span className={item.direction === "up" ? "text-status-err" : "text-brand"}>{item.direction === "up" ? "推高" : "推低"} {(item.contribution * 100).toFixed(1)}%</span></div><div className="h-2 overflow-hidden rounded-full bg-ink/[.07]"><div className="h-full rounded-full bg-brand" style={{ width: `${item.contribution * 100}%` }}/></div></summary><p className="mt-2 text-xs leading-5 text-muted">{item.detail}</p></details>)}</div> : <p className="mt-3 text-sm text-muted">当前还无法确定单一原因；建议检查输入数据、分析代码和环境版本。</p>}</section>}<div className="mt-4 font-mono text-[10px] text-subtle">new run: {result.new_run_id}</div></motion.aside>;
}

function Value({ label, value }: { label: string; value: unknown }) { return <div className="rounded-appleSm bg-surface/70 p-2"><div className="label">{label}</div><pre className="mt-1 overflow-auto">{JSON.stringify(value)}</pre></div>; }
