"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { AlertTriangle, BookOpen, Check, FileSearch, FlaskConical, Link2, Save, Search, ShieldCheck, WandSparkles, X } from "lucide-react";
import { VerifiedPreview } from "@/components/writing/VerifiedPreview";
import { api, type DocumentDetail, type Lineage, type SearchHit, type VerifyResult } from "@/lib/api";

const initialText = "# 研究结论\n\n在此撰写带可追溯锚点的结论。行内公式示例：$\\beta = 0.083$。";
const anchorPattern = /⟦((?:art|src)_[0-9a-fA-F]{4})⟧/g;

export default function WritingPage() {
  const [text, setText] = useState(initialText); const [verification, setVerification] = useState<VerifyResult>();
  const [repairTrace, setRepairTrace] = useState<NonNullable<VerifyResult["iterations"]>>([]);
  const [verifyError, setVerifyError] = useState(""); const [checking, setChecking] = useState(false); const [saving, setSaving] = useState(false);
  const [toast, setToast] = useState(""); const [searchOpen, setSearchOpen] = useState(false); const [query, setQuery] = useState(""); const [hits, setHits] = useState<SearchHit[]>([]);
  const [manualArtifact, setManualArtifact] = useState(""); const [detail, setDetail] = useState<DocumentDetail>(); const [lineage, setLineage] = useState<Lineage>();
  const [artifactIds, setArtifactIds] = useState<Record<string, string>>({});
  const editor = useRef<HTMLTextAreaElement>(null); const hydrated = useRef(false);
  useEffect(() => { const saved = localStorage.getItem("reprolab-writing-draft"); if (saved) setText(saved); const map = localStorage.getItem("reprolab-writing-artifacts"); if (map) setArtifactIds(JSON.parse(map)); hydrated.current = true; }, []);
  useEffect(() => { if (hydrated.current) localStorage.setItem("reprolab-writing-draft", text); const timer = window.setTimeout(() => { if (text.trim()) void runVerify(false); }, 700); return () => window.clearTimeout(timer); }, [text]);
  const anchors = useMemo(() => Array.from(text.matchAll(anchorPattern), (match) => match[1].toLowerCase()), [text]);
  const hasArtifact = anchors.some((item) => item.startsWith("art_"));

  async function runVerify(showError = true) { setChecking(true); if (showError) setVerifyError(""); try { setVerification(await api.verify(text)); } catch (e) { if (showError) setVerifyError((e as Error).message); } finally { setChecking(false); } }
  async function runRepair() { setChecking(true); setVerifyError(""); try { const result = await api.verify(text, ["citation", "number", "figure"], true); setRepairTrace(result.iterations ?? []); if (result.repaired_text && result.repaired_text !== text) setText(result.repaired_text); setVerification(result); } catch (e) { setVerifyError((e as Error).message); } finally { setChecking(false); } }
  function insert(value: string) { const area = editor.current; const start = area?.selectionStart ?? text.length; const end = area?.selectionEnd ?? text.length; setText(text.slice(0, start) + value + text.slice(end)); setSearchOpen(false); window.requestAnimationFrame(() => { area?.focus(); area?.setSelectionRange(start + value.length, start + value.length); }); }
  async function search() { if (!query.trim()) return; try { setHits((await api.search(query, "hybrid", {})).hits); } catch (e) { setVerifyError((e as Error).message); } }
  function insertArtifact(id: string) { const code = id.slice(0, 4).toLowerCase(); const next = { ...artifactIds, [code]: id }; setArtifactIds(next); localStorage.setItem("reprolab-writing-artifacts", JSON.stringify(next)); insert(`⟦art_${code}⟧`); }
  async function anchorClick(anchor: string) { const code = anchor.slice(5, 9).toLowerCase(); try { if (anchor.startsWith("⟦art_")) { const id = artifactIds[code]; if (id) setLineage(await api.lineage(id)); else setVerifyError("该短码缺少本地完整 UUID 映射，请通过“插入引用”重新选择产物。"); } else { const docs = await api.documents(); const source = docs.find((doc) => doc.id.startsWith(code)); if (source) setDetail(await api.document(source.id)); else setVerifyError("未找到对应文献。"); } } catch (e) { setVerifyError((e as Error).message); } }
  async function writeBack() { if (verification?.verdict !== "pass" || !hasArtifact) return; setSaving(true); setVerifyError(""); try { const result = await api.postConclusion(text, anchors); setToast(`已回写知识库 · ${result.document_id.slice(0, 8)}`); window.setTimeout(() => setToast(""), 3500); } catch (e) { setVerifyError((e as Error).message); } finally { setSaving(false); } }

  return <div className="flex h-[calc(100vh-48px)] flex-col overflow-hidden"><header className="flex min-h-16 shrink-0 flex-wrap items-center gap-2 border-b bg-white px-4 py-3 dark:border-slate-800 dark:bg-slate-950 md:px-5"><div><div className="label">Evidence-bound writing</div><h1 className="mt-1 font-semibold">写作面板</h1></div><div className="ml-auto flex flex-wrap items-center justify-end gap-2"><span className={`hidden items-center gap-2 rounded-lg px-3 py-2 text-xs md:flex ${verification?.verdict === "pass" ? "bg-emerald-50 text-emerald-700" : verification?.verdict === "fail" ? "bg-red-50 text-red-700" : "bg-slate-100 text-slate-500"}`}>{checking ? <span className="h-2 w-2 animate-pulse rounded-full bg-amber-500"/> : verification?.verdict === "pass" ? <Check size={14}/> : <ShieldCheck size={14}/>} {checking ? "正在三查 / 修复" : verification?.verdict === "pass" ? "全部可溯源" : verification?.verdict === "fail" ? `${verification.items.filter((item) => item.verdict === "fail").length} 项待修正` : "尚未校验"}</span><button onClick={() => setSearchOpen(true)} className="btn-secondary"><Link2 size={14}/>插入引用</button><button onClick={() => void runVerify()} disabled={checking} className="btn-secondary"><ShieldCheck size={14}/>运行校验</button><button onClick={() => void runRepair()} disabled={checking} className="btn-secondary"><WandSparkles size={14}/>校验并修复</button><button onClick={() => void writeBack()} disabled={verification?.verdict !== "pass" || !hasArtifact || saving} className="btn-primary"><Save size={14}/>{saving ? "回写中…" : "回写知识库"}</button></div></header>
    {verifyError && <div className="flex items-center gap-2 border-b border-red-200 bg-red-50 px-5 py-2 text-sm text-red-700"><AlertTriangle size={14}/>{verifyError}<button className="ml-auto" onClick={() => setVerifyError("")}><X size={14}/></button></div>}
    {!hasArtifact && verification?.verdict === "pass" && <div className="border-b border-amber-200 bg-amber-50 px-5 py-2 text-xs text-amber-700">回写结论至少需要一个分析产物 ⟦art_*⟧ 锚点。</div>}
    <div className="grid min-h-0 flex-1 grid-cols-1 divide-x lg:grid-cols-2"><section className="flex min-h-0 flex-col bg-white dark:bg-slate-950"><div className="flex h-10 items-center border-b px-4"><span className="label">Markdown + LaTeX 编辑</span><span className="ml-auto text-[11px] text-slate-400">{text.length} 字符 · 自动保存本地</span></div><textarea ref={editor} value={text} onChange={(e) => setText(e.target.value)} className="min-h-0 flex-1 resize-none bg-transparent p-6 font-mono text-sm leading-7 outline-none" spellCheck={false}/></section><section className="min-h-0 overflow-y-auto bg-slate-50 p-6 dark:bg-[#0B0F17]"><div className="mx-auto min-h-full max-w-3xl rounded-xl border bg-white p-7 shadow-card dark:border-slate-800 dark:bg-slate-950"><div className="mb-5 flex items-center border-b pb-3"><BookOpen size={16} className="mr-2 text-brand"/><span className="font-medium">实时预览</span><span className="ml-auto text-xs text-slate-400">点击锚点查看来源</span></div>{repairTrace.length > 0 && <div className="mb-5 space-y-2 rounded-xl border border-blue-200 bg-blue-50 p-4"><div className="label text-brand">Reflexion 修复轨迹</div>{repairTrace.map((item) => <div key={item.round} className="text-xs text-blue-900"><strong>第 {item.round} 轮 · {item.fails} 项失败</strong><div className="mt-1 text-blue-700">{item.repair_action}</div></div>)}</div>}<VerifiedPreview text={text} items={verification?.items ?? []} onAnchor={(anchor) => void anchorClick(anchor)}/>{verification?.items.some((item) => item.verdict === "fail") && <div className="mt-7 border-t pt-4"><div className="label text-red-600">校验问题</div><div className="mt-2 space-y-2">{verification.items.filter((item) => item.verdict === "fail").map((item, index) => <div key={index} className="rounded-lg border border-red-200 bg-red-50 p-3 text-xs text-red-700"><strong>{item.check}</strong> · {item.reason}<div className="mt-1 text-red-400">{item.locate}</div></div>)}</div></div>}</div></section></div>
    {toast && <div className="fixed bottom-6 right-6 z-50 flex items-center gap-2 rounded-xl bg-emerald-600 px-4 py-3 text-sm font-medium text-white shadow-xl"><Check size={16}/>{toast}</div>}
    {searchOpen && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/35 p-4" onMouseDown={() => setSearchOpen(false)}><div className="card w-full max-w-2xl p-5" onMouseDown={(e) => e.stopPropagation()}><div className="flex items-center"><div><div className="label">Insert evidence</div><h2 className="mt-1 text-lg font-semibold">插入文献或分析产物</h2></div><button onClick={() => setSearchOpen(false)} className="btn-secondary ml-auto h-8 w-8 px-0"><X size={14}/></button></div><div className="mt-5 flex gap-2"><div className="flex flex-1 items-center rounded-lg border px-3"><Search size={15} className="text-slate-400"/><input value={query} onChange={(e) => setQuery(e.target.value)} onKeyDown={(e) => e.key === "Enter" && void search()} className="h-10 flex-1 bg-transparent px-2 outline-none" placeholder="检索知识库文献…"/></div><button onClick={() => void search()} className="btn-primary">检索</button></div><div className="mt-3 max-h-64 space-y-2 overflow-y-auto">{hits.map((hit) => <button key={hit.chunk_id} onClick={() => insert(`⟦src_${hit.document_id.slice(0, 4)}⟧`)} className="w-full rounded-lg border p-3 text-left hover:border-blue-300"><div className="line-clamp-2 text-sm">{hit.content}</div><div className="mt-2 font-mono text-[10px] text-slate-400">document {hit.document_id.slice(0, 8)} · score {hit.score.toFixed(3)}</div></button>)}</div><div className="mt-5 border-t pt-4"><div className="label">分析产物 UUID</div><div className="mt-2 flex gap-2"><input value={manualArtifact} onChange={(e) => setManualArtifact(e.target.value)} className="input flex-1 font-mono text-xs" placeholder="粘贴 artifact UUID"/><button disabled={!/^[0-9a-fA-F]{4}/.test(manualArtifact)} onClick={() => insertArtifact(manualArtifact)} className="btn-secondary"><FlaskConical size={14}/>插入产物</button></div></div></div></div>}
    {detail && <div className="fixed inset-0 z-50 bg-slate-950/30" onMouseDown={() => setDetail(undefined)}><aside className="absolute bottom-0 right-0 top-0 w-full max-w-lg overflow-y-auto bg-white p-6 shadow-2xl dark:bg-slate-950" onMouseDown={(e) => e.stopPropagation()}><button onClick={() => setDetail(undefined)} className="btn-secondary float-right h-8 w-8 px-0"><X size={14}/></button><div className="label">Source document</div><h2 className="mt-2 text-lg font-semibold">{detail.title || detail.filename}</h2><div className="mt-5 break-all rounded-lg bg-slate-50 p-3 font-mono text-xs dark:bg-slate-900">{detail.storage_hash}</div></aside></div>}
    {lineage && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/35 p-4" onMouseDown={() => setLineage(undefined)}><div className="card max-h-[75vh] w-full max-w-2xl overflow-y-auto p-5" onMouseDown={(e) => e.stopPropagation()}><button onClick={() => setLineage(undefined)} className="btn-secondary float-right h-8 w-8 px-0"><X size={14}/></button><div className="label">Artifact lineage</div><h2 className="mt-2 text-lg font-semibold">完整血缘链</h2><div className="mt-5 grid gap-2 sm:grid-cols-3">{lineage.nodes.map((node) => <div key={node.id} className="rounded-lg border p-3"><span className="text-[10px] uppercase text-brand">{node.type}</span><div className="mt-1 truncate text-sm font-medium">{node.label}</div></div>)}</div></div></div>}
  </div>;
}
