"use client";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { motion } from "framer-motion";
import { AlertTriangle, BarChart3, Check, ChevronDown, ChevronRight, Code2, Database, ExternalLink, FileSpreadsheet, Play, RotateCcw, Send, Sparkles, Terminal, X } from "lucide-react";
import { AnchoredMarkdown } from "@/components/anchor/AnchoredMarkdown";
import { API_BASE, api, streamChat, type ChatEvent, type DocumentDetail, type Lineage } from "@/lib/api";

type EventItem = ChatEvent & { id: string };
type ArtifactData = { artifact_id: string; kind: string; value_json: any; figure_url?: string | null; anchor: string };
const examples = ["比较不同组的均值并绘图", "分析两个变量的相关性", "建立回归模型并解释系数"];

export default function AnalysisPage() {
  const [datasets, setDatasets] = useState<DocumentDetail[]>([]); const [selected, setSelected] = useState<string[]>([]);
  const [events, setEvents] = useState<EventItem[]>([]); const [message, setMessage] = useState(""); const [running, setRunning] = useState(false);
  const [error, setError] = useState(""); const [conversation, setConversation] = useState<string>(); const [activeArtifact, setActiveArtifact] = useState<ArtifactData>();
  const [lineage, setLineage] = useState<Lineage>(); const [lineageLoading, setLineageLoading] = useState(false); const endRef = useRef<HTMLDivElement>(null); const abortRef = useRef<AbortController>();

  useEffect(() => { void (async () => { try { const docs = await api.documents("other"); const details = await Promise.all(docs.map((doc) => api.document(doc.id))); setDatasets(details.filter((doc) => doc.dataset_id)); } catch (e) { setError((e as Error).message); } })(); }, []);
  useEffect(() => { endRef.current?.scrollIntoView({ behavior: "smooth" }); }, [events]);
  const artifacts = useMemo(() => events.filter((item) => item.event === "artifact").map((item) => item.data as ArtifactData), [events]);

  const send = useCallback(async (text = message) => {
    if (!text.trim() || running) return; setMessage(""); setError(""); setRunning(true);
    setEvents((items) => [...items, { id: crypto.randomUUID(), event: "message", data: { text: text.trim(), citations: [], user: true } }]);
    const controller = new AbortController(); abortRef.current = controller;
    try {
      await streamChat({ conversation_id: conversation, message: text.trim(), dataset_ids: selected }, (incoming) => {
        setEvents((items) => [...items, { ...incoming, id: crypto.randomUUID() }]);
        if (incoming.event === "artifact") setActiveArtifact(incoming.data as ArtifactData);
        if (incoming.event === "done") setConversation(incoming.data.conversation_id);
      }, controller.signal);
    } catch (e) { if ((e as Error).name !== "AbortError") setError((e as Error).message); }
    finally { setRunning(false); abortRef.current = undefined; }
  }, [conversation, message, running, selected]);

  async function showLineage(id: string) { setLineageLoading(true); try { setLineage(await api.lineage(id)); } catch (e) { setError((e as Error).message); } finally { setLineageLoading(false); } }
  function toggleDataset(id: string) { setSelected((items) => items.includes(id) ? items.filter((item) => item !== id) : [...items, id]); }
  function anchorClick(anchor: string) { const artifact = artifacts.find((item) => item.anchor.toLowerCase() === anchor.toLowerCase()); if (artifact) { setActiveArtifact(artifact); void showLineage(artifact.artifact_id); } }

  return <div className="flex h-[calc(100vh-48px)] min-h-[640px] overflow-hidden">
    <aside className="hidden w-[260px] shrink-0 overflow-y-auto border-r bg-white p-4 dark:border-slate-800 dark:bg-slate-950 lg:block">
      <div className="label">当前分析</div><h1 className="mt-1 text-lg font-semibold">数据与会话</h1>
      <div className="mt-6 flex items-center gap-2 text-sm font-medium"><Database size={15} className="text-brand"/>数据集 <span className="ml-auto text-xs text-slate-400">{selected.length} 已选</span></div>
      <div className="mt-2 space-y-2">{datasets.length === 0 ? <div className="rounded-lg border border-dashed p-3 text-xs leading-5 text-slate-400">请先在知识库上传 CSV/XLSX 数据集。</div> : datasets.map((dataset) => <button key={dataset.id} onClick={() => dataset.dataset_id && toggleDataset(dataset.dataset_id)} className={`w-full rounded-lg border p-3 text-left transition ${dataset.dataset_id && selected.includes(dataset.dataset_id) ? "border-blue-300 bg-blue-50 dark:bg-blue-950/30" : "hover:bg-slate-50 dark:hover:bg-slate-900"}`}><div className="flex items-center gap-2"><FileSpreadsheet size={15} className="text-emerald-600"/><span className="min-w-0 flex-1 truncate text-sm font-medium">{dataset.filename}</span>{dataset.dataset_id && selected.includes(dataset.dataset_id) && <Check size={14} className="text-brand"/>}</div><div className="mt-2 text-[11px] text-slate-400">{dataset.schema_json?.row_count ?? 0} 行 · {dataset.schema_json?.column_count ?? 0} 列</div></button>)}</div>
      <div className="mt-7 flex items-center gap-2 text-sm font-medium"><ChevronDown size={14}/>会话状态</div><div className="mt-2 rounded-lg bg-slate-50 p-3 text-xs dark:bg-slate-900"><div className="text-slate-400">Conversation ID</div><div className="mt-1 truncate font-mono">{conversation ?? "新会话"}</div><div className="mt-3 flex items-center gap-2"><span className={`h-2 w-2 rounded-full ${running ? "animate-pulse bg-amber-500" : "bg-emerald-500"}`}/>{running ? "Agent 正在执行" : "准备就绪"}</div></div>
    </aside>
    <main className="relative flex min-w-0 flex-1 flex-col bg-[#F8FAFC] dark:bg-[#0B0F17]">
      <div className="flex h-14 shrink-0 items-center border-b bg-white px-5 dark:border-slate-800 dark:bg-slate-950"><div><div className="font-semibold">分析对话</div><div className="text-xs text-slate-400">规划 → 代码 → 执行 → 可溯源结论</div></div><div className="ml-auto flex items-center gap-2 text-xs text-slate-400"><span className="h-2 w-2 rounded-full bg-emerald-500"/>持久 Python 3.11 kernel</div></div>
      <div className="flex-1 overflow-y-auto px-4 py-6 md:px-8"><div className="mx-auto max-w-3xl">
        {events.length === 0 ? <div className="grid min-h-[55vh] place-items-center text-center"><div><span className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-blue-50 text-brand dark:bg-blue-950"><Sparkles size={24}/></span><h2 className="mt-4 text-xl font-semibold">从一个科研问题开始</h2><p className="mx-auto mt-2 max-w-lg text-sm leading-6 text-slate-500">Agent 会读取所选数据，动态编写 Python、运行分析，并把每个数字和图绑定到数据、代码与环境。</p><div className="mt-5 flex flex-wrap justify-center gap-2">{examples.map((item) => <button key={item} onClick={() => setMessage(item)} className="rounded-full border bg-white px-3 py-2 text-xs text-slate-600 hover:border-blue-300 hover:text-brand dark:bg-slate-900">{item}</button>)}</div></div></div> : <div className="space-y-4">{events.map((item) => <EventCard key={item.id} item={item} onArtifact={(artifact) => setActiveArtifact(artifact)} onAnchor={anchorClick} onLineage={showLineage}/>)}</div>}
        {running && <div className="mt-4 flex items-center gap-2 text-xs text-slate-400"><span className="flex gap-1"><i className="h-1.5 w-1.5 animate-bounce rounded-full bg-brand [animation-delay:-.2s]"/><i className="h-1.5 w-1.5 animate-bounce rounded-full bg-brand [animation-delay:-.1s]"/><i className="h-1.5 w-1.5 animate-bounce rounded-full bg-brand"/></span>Agent 正在推进下一步</div>}
        {error && <div role="alert" className="mt-4 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700"><AlertTriangle className="mr-2 inline" size={15}/>{error}</div>}<div ref={endRef}/>
      </div></div>
      <div className="shrink-0 border-t bg-white p-4 dark:border-slate-800 dark:bg-slate-950"><div className="mx-auto max-w-3xl"><div className="rounded-xl border bg-white p-2 shadow-card focus-within:border-blue-300 dark:border-slate-700 dark:bg-slate-900"><textarea value={message} onChange={(e) => setMessage(e.target.value)} onKeyDown={(e) => { if ((e.metaKey || e.ctrlKey) && e.key === "Enter") void send(); }} rows={2} className="w-full resize-none bg-transparent px-2 py-1 outline-none" placeholder={selected.length ? "描述你想分析的问题…" : "可先选择数据集，再描述分析问题…"}/><div className="flex items-center px-1 pt-1"><span className="text-[11px] text-slate-400">⌘↵ 发送 · 所有产物自动登记溯源</span>{running ? <button onClick={() => abortRef.current?.abort()} className="btn-secondary ml-auto h-8"><X size={14}/>停止</button> : <button onClick={() => void send()} disabled={!message.trim()} className="btn-primary ml-auto h-8"><Send size={14}/>发送</button>}</div></div></div></div>
    </main>
    <aside className="hidden w-[360px] shrink-0 overflow-y-auto border-l bg-white p-4 dark:border-slate-800 dark:bg-slate-950 xl:block"><div className="flex items-center justify-between"><div><div className="label">Artifact preview</div><h2 className="mt-1 font-semibold">产物预览</h2></div><span className="rounded-md bg-slate-100 px-2 py-1 text-xs text-slate-500 dark:bg-slate-800">{artifacts.length}</span></div>{activeArtifact ? <ArtifactPreview artifact={activeArtifact} onLineage={showLineage}/> : <div className="mt-5 rounded-xl border border-dashed p-6 text-center text-sm text-slate-400"><BarChart3 className="mx-auto mb-3" size={24}/>执行分析后，图、表和数字会在这里出现。</div>}</aside>
    {(lineage || lineageLoading) && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/30 p-4" onMouseDown={() => setLineage(undefined)}><div className="card max-h-[80vh] w-full max-w-2xl overflow-y-auto p-5" onMouseDown={(e) => e.stopPropagation()}><div className="flex items-center"><div><div className="label">Provenance ledger</div><h2 className="mt-1 text-lg font-semibold">完整溯源链</h2></div><button onClick={() => setLineage(undefined)} className="btn-secondary ml-auto h-8 w-8 px-0"><X size={15}/></button></div>{lineageLoading ? <div className="mt-5 h-52 animate-pulse rounded-xl bg-slate-100 dark:bg-slate-800"/> : lineage && <div className="mt-5"><div className="grid gap-2 sm:grid-cols-3">{lineage.nodes.map((node) => <div key={node.id} className="rounded-lg border p-3"><span className="rounded bg-blue-50 px-1.5 py-0.5 text-[10px] uppercase text-brand">{node.type}</span><div className="mt-2 truncate text-sm font-medium">{node.label}</div><div className="mt-1 truncate font-mono text-[10px] text-slate-400">{node.id}</div></div>)}</div><div className="mt-4 space-y-2">{lineage.edges.map((edge, index) => <div key={index} className="flex items-center gap-2 rounded-lg bg-slate-50 px-3 py-2 font-mono text-xs dark:bg-slate-900"><span>{edge.from.slice(0, 8)}</span><ChevronRight size={13}/><span className="rounded bg-white px-2 py-1 text-brand dark:bg-slate-800">{edge.relation}</span><ChevronRight size={13}/><span>{edge.to.slice(0, 8)}</span></div>)}</div></div>}</div></div>}
  </div>;
}

function EventCard({ item, onArtifact, onAnchor, onLineage }: { item: EventItem; onArtifact: (artifact: ArtifactData) => void; onAnchor: (anchor: string) => void; onLineage: (id: string) => void }) {
  if (item.data.user) return <div className="ml-auto max-w-[80%] rounded-xl rounded-br-sm bg-slate-900 px-4 py-3 text-sm text-white dark:bg-slate-100 dark:text-slate-900">{item.data.text}</div>;
  if (item.event === "plan") return <div className="card p-4"><div className="mb-3 flex items-center gap-2 text-xs font-semibold uppercase tracking-wide text-brand"><Sparkles size={14}/>执行计划</div><ol className="space-y-2">{item.data.steps.map((step: any, index: number) => <li key={index} className="flex gap-3"><span className="grid h-6 w-6 shrink-0 place-items-center rounded-full bg-blue-50 text-xs font-semibold text-brand">{index + 1}</span><div><div className="text-sm font-medium">{step.title}</div><div className="mt-0.5 text-xs text-slate-500">{step.rationale}</div></div></li>)}</ol></div>;
  if (item.event === "thinking") return <details className="rounded-lg border bg-white px-4 py-3 dark:border-slate-800 dark:bg-slate-900"><summary className="cursor-pointer text-xs font-medium text-slate-500">思考与判断</summary><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300">{item.data.text}</p></details>;
  if (item.event === "code") return <div className="overflow-hidden rounded-xl border bg-[#0F172A] text-slate-100"><div className="flex h-9 items-center border-b border-slate-700 px-3 text-xs text-slate-400"><Code2 className="mr-2" size={14}/>Python <button className="ml-auto hover:text-white">编辑</button></div><pre className="max-h-80 overflow-auto p-4 font-mono text-xs leading-6"><code>{item.data.code}</code></pre></div>;
  if (item.event === "run") return <div className={`flex items-start gap-3 rounded-lg border p-3 ${item.data.status === "success" ? "border-emerald-200 bg-emerald-50/60" : "border-red-200 bg-red-50"}`}><span className={`mt-0.5 grid h-6 w-6 place-items-center rounded-full ${item.data.status === "success" ? "bg-emerald-600 text-white" : "bg-red-600 text-white"}`}>{item.data.status === "success" ? <Check size={14}/> : <AlertTriangle size={13}/>}</span><div className="min-w-0 flex-1"><div className="text-sm font-medium">运行{item.data.status === "success" ? "完成" : "失败"}</div><pre className="mt-1 max-h-28 overflow-auto whitespace-pre-wrap font-mono text-xs text-slate-600">{item.data.stdout || "无标准输出"}</pre><div className="mt-1 font-mono text-[10px] text-slate-400">run {item.data.run_id}</div></div></div>;
  if (item.event === "artifact") { const artifact = item.data as ArtifactData; return <motion.button initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} onClick={() => onArtifact(artifact)} className="card w-full border-blue-100 p-4 text-left hover:border-blue-300"><div className="flex items-center gap-2"><BarChart3 size={16} className="text-brand"/><span className="font-medium">{artifact.kind} 产物</span><span className="ml-auto font-mono text-xs text-brand">{artifact.anchor}</span></div>{artifact.figure_url ? <img className="mt-3 max-h-64 w-full rounded-lg border object-contain" src={`${API_BASE.replace(/\/api\/v1$/, "")}${artifact.figure_url}`} alt="分析产物"/> : <pre className="mt-3 max-h-36 overflow-auto rounded-lg bg-slate-50 p-3 font-mono text-xs dark:bg-slate-900">{JSON.stringify(artifact.value_json, null, 2)}</pre>}<span onClick={(event) => { event.stopPropagation(); void onLineage(artifact.artifact_id); }} className="mt-3 inline-flex items-center gap-1 text-xs font-medium text-brand"><ExternalLink size={12}/>查看来源</span></motion.button>; }
  if (item.event === "message") return <div className="card p-5"><div className="mb-3 flex items-center gap-2 text-xs font-semibold uppercase tracking-wide text-emerald-600"><Check size={14}/>分析结论</div><AnchoredMarkdown text={item.data.text} onAnchor={onAnchor}/></div>;
  return null;
}

function ArtifactPreview({ artifact, onLineage }: { artifact: ArtifactData; onLineage: (id: string) => void }) {
  return <motion.div key={artifact.artifact_id} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} className="mt-5"><div className="card overflow-hidden"><div className="flex items-center border-b px-4 py-3"><BarChart3 size={16} className="mr-2 text-brand"/><span className="font-medium">{artifact.kind}</span><span className="ml-auto font-mono text-xs text-brand">{artifact.anchor}</span></div>{artifact.figure_url ? <img className="max-h-72 w-full object-contain p-3" src={`${API_BASE.replace(/\/api\/v1$/, "")}${artifact.figure_url}`} alt="当前产物"/> : <pre className="max-h-72 overflow-auto p-4 font-mono text-xs">{JSON.stringify(artifact.value_json, null, 2)}</pre>}</div><div className="mt-3 grid grid-cols-2 gap-2"><button onClick={() => void onLineage(artifact.artifact_id)} className="btn-primary"><ExternalLink size={14}/>查看来源</button><button className="btn-secondary"><RotateCcw size={14}/>重跑</button></div><div className="mt-4 rounded-lg border bg-slate-50 p-3 dark:bg-slate-900"><div className="label">Artifact ID</div><div className="mt-1 break-all font-mono text-[11px] text-slate-500">{artifact.artifact_id}</div></div></motion.div>;
}

